eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true
  instance:
    appname: eureka-producer #对应服务的application
    instance-id: producer # 自定义服务名称信息对应页面上status
    prefer-ip-address: true #设置访问路径是否显示ip地址
    hostname: localhost
spring:
  application:
    name: client-test # 设置应用名称,若instance.appname没设置会采用这个作为应用名称 ps最好不要使用下划线'_'否则消费端调用时会报错
server:
  port: 8888

